export const CONSTANTS = {
  SOCKET_EVENTS: {
    ROOM_JOIN: 'room:join',
    ROOM_LEAVE: 'room:leave',
    ROOM_FULL: 'room:full',
    WEBRTC_OFFER: 'webrtc:offer',
    WEBRTC_ANSWER: 'webrtc:answer',
    WEBRTC_ICE: 'webrtc:ice-candidate',
    MEDIA_TOGGLE_AUDIO: 'media:toggle-audio',
    MEDIA_TOGGLE_VIDEO: 'media:toggle-video',
    MEDIA_SCREEN_START: 'media:screen-share-start',
    MEDIA_SCREEN_STOP: 'media:screen-share-stop',
    CHAT_MESSAGE: 'chat:message',
    CHAT_REACTION: 'chat:reaction',
    AI_TRANSCRIPTION_CHUNK: 'ai:transcription-chunk',
    AI_SUMMARY_READY: 'ai:summary-ready',
    AI_ASSISTANT_RESPONSE: 'ai:assistant-response',
    PARTICIPANT_JOINED: 'participant:joined',
    PARTICIPANT_LEFT: 'participant:left',
    PARTICIPANT_LIST: 'participant:list',
  },
};
